[project]
name = "yc-map-reviews-parser"
version = "0.1.0"
description = "Yandex map reviews parser"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "mypy>=1.16.1",
]
